import abc
from enum import Enum
from functools import lru_cache
import os
from pathlib import Path
from typing import Any, Callable, TypeAlias, Union

from dotenv import dotenv_values
from pydantic import BaseSettings
from pydantic.env_settings import SettingsSourceCallable
import yaml

VERSION = '0.2.0'

ENV_PREFIX = 'C4GH_RECRYPTOR_'
ENV_FILE = '.env'
LOCALHOST = 'localhost'

DEFAULT_WORKING_DIR_USER = 'c4gh_recryptor_user'
DEFAULT_WORKING_DIR_COMPUTE = 'c4gh_recryptor_compute'
DEFAULT_YML_CONFIG_FILENAME = 'c4gh_config.yml'
DEFAULT_HOST = LOCALHOST
DEFAULT_PORT_USER = 61357
DEFAULT_PORT_COMPUTE = 61358
DEFAULT_SSL_CERTFILE = 'localhost.pem'
DEFAULT_SSL_KEYFILE = 'localhost-key.pem'
DEFAULT_PRIVATE_KEY_PASSPHRASE = 'Override me using C4GH_RECRYPTOR_PRIVATE_KEY_PASSPHRASE as ' \
                                 'environment variable or in .env!'
DEFAULT_PRIVATE_KEY_COMMENT = 'Generated by crypt4gh-recryptor-service!'
DEFAULT_USER_PRIVATE_KEY_FILE = 'user_key.priv'
DEFAULT_USER_PUBLIC_KEY_FILE = 'user_key.pub'
DEFAULT_COMPUTE_PRIVATE_KEY_FILE = 'compute_node_key.priv'
DEFAULT_COMPUTE_PUBLIC_KEY_FILE = 'compute_node_key.pub'

USER_KEYS_DIR = 'user_keys'
COMPUTE_KEYS_DIR = 'compute_keys'
HEADERS_DIR = 'headers'
CERT_DIR = 'certs'

_builtin_dict: TypeAlias = dict


class ServerMode(str, Enum):
    USER = 'user'
    COMPUTE = 'compute'


C4ghSettingsSourceCallable = Callable[['Settings'], dict[str, Any]]


class BaseConfig:
    env_file: str = ENV_FILE
    env_prefix: str = ENV_PREFIX
    use_enum_values: bool = True
    underscore_attrs_are_private: bool = True
    validate_assignment: bool = True

    @classmethod
    def customise_sources(
        cls,
        init_settings: SettingsSourceCallable,
        env_settings: SettingsSourceCallable,
        file_secret_settings: SettingsSourceCallable,
    ) -> tuple[C4ghSettingsSourceCallable, ...]:
        store_env_settings = get_store_env_settings_callable(env_settings)
        return yml_config_setting, store_env_settings,


class Settings(BaseSettings):
    _environ_vars: dict[str, Any] = {}
    _overridden_by_environ_vars: dict[str, Any] = {}

    host: str = DEFAULT_HOST
    port: int
    server_mode: ServerMode
    ssl_certfile: str = DEFAULT_SSL_CERTFILE
    ssl_keyfile: str = DEFAULT_SSL_KEYFILE
    private_key_passphrase: str = DEFAULT_PRIVATE_KEY_PASSPHRASE
    private_key_comment: str = DEFAULT_PRIVATE_KEY_COMMENT
    dev_mode: bool = False

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._override_by_environ_vars()

    def _override_by_environ_vars(self):
        for key, val in self._environ_vars.items():
            self._overridden_by_environ_vars[key] = getattr(self, key)
            setattr(self, key, val)

    def update_environ_vars(self, environ_vars: _builtin_dict[str, Any]):
        self._environ_vars.update(environ_vars)

    def dict(self, *args: Any, **kwargs: Any) -> dict[str, Any]:
        super_dict = super().dict(*args, **kwargs)
        for key, val in self._overridden_by_environ_vars.items():
            if key in super_dict:
                super_dict[key] = val
        return super_dict

    @property
    @abc.abstractmethod
    def working_dir(self) -> Path:
        pass

    @property
    def yml_config_file_path(self) -> Path:
        return _get_yml_config_file_path(self.working_dir)

    @property
    def compute_keys_dir(self) -> Path:
        return Path(self.working_dir, COMPUTE_KEYS_DIR)

    @property
    def headers_dir(self) -> Path:
        return Path(self.working_dir, HEADERS_DIR)

    @property
    def cert_dir(self) -> Path:
        return Path(self.working_dir, CERT_DIR)

    @property
    def localhost_certfile_path(self) -> Path:
        return Path(self.cert_dir, self.ssl_certfile)

    @property
    def localhost_keyfile_path(self) -> Path:
        return Path(self.cert_dir, self.ssl_keyfile)


class UserSettings(Settings):
    server_mode: ServerMode = ServerMode.USER
    port: int = DEFAULT_PORT_USER
    compute_host: str = DEFAULT_HOST
    compute_port: int = DEFAULT_PORT_COMPUTE
    user_private_key: str = DEFAULT_USER_PRIVATE_KEY_FILE
    user_public_key: str = DEFAULT_USER_PUBLIC_KEY_FILE

    @property
    def working_dir(self) -> Path:
        return _get_working_dir(ServerMode.USER)

    @property
    def user_keys_dir(self) -> Path:
        return Path(self.working_dir, USER_KEYS_DIR)

    @property
    def user_private_key_path(self) -> Path:
        return Path(self.user_keys_dir, DEFAULT_USER_PRIVATE_KEY_FILE)

    @property
    def user_public_key_path(self) -> Path:
        return Path(self.user_keys_dir, DEFAULT_USER_PUBLIC_KEY_FILE)

    @property
    def compute_public_key_path(self) -> Path:
        return Path(self.compute_keys_dir, DEFAULT_COMPUTE_PUBLIC_KEY_FILE)

    class Config(BaseConfig):
        pass


class ComputeSettings(Settings):
    server_mode: ServerMode = ServerMode.COMPUTE
    port: int = DEFAULT_PORT_COMPUTE

    @property
    def working_dir(self) -> Path:
        return _get_working_dir(ServerMode.COMPUTE)

    class Config(BaseConfig):
        pass


@lru_cache
def get_user_settings() -> UserSettings:
    return UserSettings()


@lru_cache
def get_compute_settings() -> ComputeSettings:
    return ComputeSettings()


def get_settings(server_mode: ServerMode) -> Union[UserSettings, ComputeSettings]:
    if server_mode == ServerMode.USER:
        return get_user_settings()
    else:
        return get_compute_settings()


def get_store_env_settings_callable(
        env_settings_func: SettingsSourceCallable) -> C4ghSettingsSourceCallable:
    def store_env_settings(settings: Settings) -> dict[str, Any]:
        env_settings = env_settings_func(settings)
        settings.update_environ_vars(env_settings)
        return {}

    return store_env_settings


def yml_config_setting(settings: Settings) -> dict[str, Any]:
    with open(settings.yml_config_file_path) as f:
        ret = yaml.safe_load(f)
        if ret:
            return ret
        return {}


def _get_working_dir(server_mode: ServerMode) -> Path:
    default_working_dir_attr = f'DEFAULT_WORKING_DIR_{server_mode.value.upper()}'
    if env_working_dir := dotenv_values().get(default_working_dir_attr):
        return Path(env_working_dir)
    else:
        return Path.cwd().joinpath(Path(globals()[default_working_dir_attr]))


def _get_yml_config_file_path(working_dir: Path) -> Path:
    return Path(working_dir, DEFAULT_YML_CONFIG_FILENAME)


def _ensure_dirs(dir_path: Path):
    if not dir_path.exists():
        dir_path.mkdir(mode=0o700, parents=True)


def setup_files(server_mode: ServerMode):
    working_dir = _get_working_dir(server_mode)
    yml_config_file_path = _get_yml_config_file_path(working_dir)

    _ensure_dirs(working_dir)
    if server_mode == ServerMode.USER:
        _ensure_dirs(Path(working_dir, USER_KEYS_DIR))

    _ensure_dirs(Path(working_dir, COMPUTE_KEYS_DIR))
    _ensure_dirs(Path(working_dir, HEADERS_DIR))
    _ensure_dirs(Path(working_dir, CERT_DIR))

    if not os.path.exists(yml_config_file_path):
        with open(yml_config_file_path, 'w') as f:
            f.write('')
        yml_config_file_path.chmod(mode=0o600)

    settings = get_settings(server_mode).dict()

    with open(yml_config_file_path, 'w') as f:
        yaml.safe_dump(settings, f)
